
export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

export const STATUS_SUCCESS = 200;

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILED = 'FETCH_CATEGORIES_FAILED';

export const CHECK_CALL_API = "CHECK_CALL_API";

export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED';

export const SET_HOT_TREND_DATA = 'SET_HOT_TREND_DATA';
export const SET_MEN_CLOTHES_DATA = 'SET_MEN_CLOTHES_DATA';
export const SET_WOMEN_CLOTHES_DATA = 'SET_WOMEN_CLOTHES_DATA';
export const SET_KIDS_CLOTHES_DATA = 'SET_KIDS_CLOTHES_DATA';
export const SET_HANDBAG_AND_SHOES_DATA = 'SET_HANDBAG_AND_SHOES_DATA';

export const FETCH_NEWS = 'FETCH_NEWS';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAILED = 'FETCH_NEWS_FAILED';

export const FETCH_BRANDS = 'FETCH_BRANDS';
export const FETCH_BRANDS_SUCCESS = 'FETCH_BRANDS_SUCCESS';
export const FETCH_BRANDS_FAILED = 'FETCH_BRANDS_FAILED';

export const CHANGE_PAGE = 'CHANGE_PAGE';
export const CHANGE_FILTER_PRODUCT_DATA = 'CHANGE_FILTER_PRODUCT_DATA';
export const ADD_BRAND_ID = 'ADD_BRAND_ID';
export const REMOVE_BRAND_ID = 'REMOVE_BRAND_ID';
export const CHANGE_PRICE = 'CHANGE_PRICE';
export const CHANGE_RATING = 'CHANGE_RATING';
export const RESET_FILTER_PRODUCT = 'RESET_FILTER_PRODUCT';
export const SORT_PRODUCT = 'SORT_PRODUCT';

export const DETAIL_PRODUCT = 'DETAIL_PRODUCT';
export const RELATED_PRODUCT = 'RELATED_PRODUCT';
export const CHANGE_QUANTITY_DETAIL = 'CHANGE_QUANTITY_DETAIL';
export const CHANGE_SIZE_DETAIL = 'CHANGE_SIZE_DETAIL';
export const CHANGE_IMAGE_DETAIL = 'CHANGE_IMAGE_DETAIL';

export const FETCH_SIZES = 'FETCH_SIZES';
export const FETCH_SIZES_SUCCESS = 'FETCH_SIZES_SUCCESS';
export const FETCH_SIZES_FAILED = 'FETCH_SIZES_FAILED';